# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Jonathon Kuntz
description: |
  Sharks + Stable Isotopes<br /><br />
  PhD Student at the University of California Merced<br /><br />
  California SeaGrant Fellow
owner:
  name: Jonathon Kuntz # or company name
  url: "https://jonathonkuntz.github.io/" # your URL
first_published: 2022 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
url: "https://jonathonkuntz.github.io/" # the base hostname & protocol for this site
baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: About Me  
  text: I am a stable isotope ecologist interested in the life histories of sharks. I am pursuing my PhD in the Kim lab at University of California, Merced where I use chronological tissues such as teeth, eye lenses, and vertebrae to understand shark movement and foraging across space and time. I was named a 2022 California Sea Grant Fellow for my continued work on Leopard Shark (<i>Triakis semifasciata</i>) ecology in the San Francisco Estuary.<br /><br />In 2017, I received a BSc in environmental and organismal biology from the University of Utah. I was subsequently hired as an soil science intern with the USFS's Institute of Pacific Island Forestry (IPIF) working in Mangrove ecosystems, and later transitioned to a full time hybrid ecosystem position at the University of Hawai'i, Hilo. In 2018 I accepted a technician position with UC Davis's Otolith Geochemistry and Fish Ecology Laboratory (OGFL) where I conducted otolith strontium stable isotope and trace elemental analsysis before eventually starting my PhD in 2020 at UC Merced.
# - displayed at the bottom
closing-head: Please get in touch!
closing-para: If you have any questions on anything, don't hestitate to reach out via the icons below.

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/Shark_eye_sci
  github: https://github.com/jonathonkuntz
  email: jkuntz@ucmerced.edu # you can configure and use this contact page or use your email addy
  #linkedin-square:
  #facebook-official:
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# - title for your blog's featured posts
features-title: Featured topics

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# Github pages posts future posts by default.
# You'll want to move the user guide posts to _drafts if you set this to true.
future: false

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
